# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-04 01:53
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FIRST', 'first'), ('second', 'second')], max_length=12),
        ),
    ]
